### ISSUE TITLE
Error 401 right at the beginning of the execution

### ISSUE THREAD

**Issue by cairobraga** [SirMartin/TvTimeToRyot#1]
Hi there!

After following the instructions and editing the CSVs TVTime sent me so they'd fit the examples given in the README, I ran the script but it gives me a 401 code with this output:

```shell
[user]@[machine]:~/TVTime2RYOT$ node tvtime-to-ryot.js
/home/moonark/TVTime2RYOT/node_modules/node-themoviedb/dist/utils/errors.js:23
        var _this = _super.call(this, message) || this;
                           ^

Error
    at UnauthorizedError.BaseError [as constructor] (/home/moonark/TVTime2RYOT/node_modules/node-themoviedb/dist/utils/errors.js:23:28)
    at new UnauthorizedError (/home/moonark/TVTime2RYOT/node_modules/node-themoviedb/dist/utils/errors.js:41:23)
    at Object.default (/home/moonark/TVTime2RYOT/node_modules/node-themoviedb/dist/utils/catchHTTPErrors.js:33:23)
    at /home/moonark/TVTime2RYOT/node_modules/node-themoviedb/dist/utils/createEndpoints.js:111:46
    at step (/home/moonark/TVTime2RYOT/node_modules/node-themoviedb/dist/utils/createEndpoints.js:33:23)
    at Object.throw (/home/moonark/TVTime2RYOT/node_modules/node-themoviedb/dist/utils/createEndpoints.js:14:53)
    at rejected (/home/moonark/TVTime2RYOT/node_modules/node-themoviedb/dist/utils/createEndpoints.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: undefined,
  errorCode: 401
}

Node.js v18.19.1
``` 

Any thoughts?

Thanks in advance!

**Comment by SirMartin** [comment]
Hello, I tested and work fine.

I think maybe you have multiple keys on TMDB and are picking the wrong type. If I try with an Access Token, I get the same error as you.

You have to use the one labelled as API Key Auth, you should be able to see all your keys here: https://developer.themoviedb.org/reference/intro/authentication

I have updated the README to clarify how to obtain a key, and which one to use on the script.

I hope this works for you.
